---
- hosts: all
  gather_facts: false
  vars:
    - httpd_port: 80
    - ssh_port: 22
    - repository: https://github.com/dfederlein/webexample.git
    
  tasks:
  
  - name: start firewalld 
    service: name=firewalld state=started enabled=yes 

  - name: enable ssh in firewalld
    firewalld: port={{ ssh_port }}/tcp permanent=true state=enabled immediate=yes
    
  - name: install epel
    yum: name=epel-release state=present
    
  - name: install apache
    yum: name=httpd state=present

  - name: insert firewalld rule for httpd
    firewalld: port={{ httpd_port }}/tcp permanent=true state=enabled immediate=yes
  
  - name: get rid of existing html index page
    file: path=/var/www/html/index.html state=absent

  - name: copy the code from repository
    git: repo={{ repository }} dest=/var/www/html/

  - name: start and enable apache
    service: name=httpd state=started enabled=yes
  
    
