---
- hosts: all
  gather_facts: false
  become: true
  become_user: root
  become_method: sudo
  vars:
    - https_port: 443
    - httpd_port: 80
    - ssh_port: 22
    - repository: https://github.com/dfederlein/webexample.git
    
  tasks:
  
  - local_action:  wait_for port=22 host="{{ ansible_ssh_host | default(inventory_hostname) }}" search_regex=OpenSSH delay=10
    become: false
    
  - name: install epel
    yum: name=epel-release state=present
  
  - name: install git
    yum: name=git state=present
    
  - name: install apache
    yum: name=httpd state=present
  
  - name: get rid of existing html index page
    file: path=/var/www/html/index.html state=absent

  - name: copy the code from repository
    git: repo={{ repository }} dest=/var/www/html/ force=yes

  - name: start and enable apache
    service: name=httpd state=started enabled=yes
  
    
