---
- hosts: localhost
  gather_facts: false
  vars:
    - region: us-east-2
    - project_name: dfed-demo

  tasks:
  - ec2_vpc:
      state: present
      region: "{{ region }}"
      cidr_block: 10.250.0.0/16
      resource_tags:
        tool: ansible
        Name: "{{ project_name }}-vpc"
      subnets:
        - cidr: 10.250.1.0/24
          az: "{{ region }}a"
          resource_tags:
            tool: ansible
            Name: subnet-a
      internet_gateway: True
      route_tables:
        - subnets:
           - 10.250.1.0/24
          routes:
            - dest: 0.0.0.0/0
              gw: igw
              
  - debug: msg="Created VPC named {{ project_name }}-vpc"

  - ec2_vpc_net_facts:
      region: "{{ region }}"
      filters:
        "tag:Name": "{{ project_name }}-vpc"
    register: network

  - debug: msg="{{ network }}"
    
  - set_fact:
      vpc_id: "{{ network.vpcs[0].id }}"

  - ec2_vpc_subnet_facts:
      region: "{{ region }}"
      filters:
        vpc-id: "{{ vpc_id }}"
    register: vpc_nets
    
  - set_fact:
      subnets: "{{ vpc_nets.subnets | map(attribute='id') | list }}"
 
  - debug: var=subnets[0]
      
  - ec2_group:
      name: webservers
      region: "{{ region }}"
      description: Security group to allow public HTTP/HTTPS traffic
      vpc_id: "{{ vpc_id }}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: 0.0.0.0/0
    register: web_sg
  - debug: msg=Created VPC security group called webservers, ID {{ web_sg.group_id }} to take web traffic
  
  - ec2:
      key_name: dfed
      group: webservers
      vpc_subnet_id: "{{ subnets[0] }}"
      instance_type: t2.micro
      image: ami-6a2d760f
      wait: true
      region: us-east-2
      exact_count: 1
      count_tag:
        Count: dfed-demo
      instance_tags:
        Name: dfed
        Count: dfed-demo
        register: ec2
